spring.application.name=ParkeoX

# -----------CONNEXION A DATABASE---------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/parkeox_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

#--------------------------------------------------------

#CONFIGURACION JPA AUTOMATIZADO

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect